// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9SrsGicW-GHCGY9jAYO3QfUKYi_reoA',
    appId: '1:368967870861:web:9d79c4246d36c36f08f5c4',
    messagingSenderId: '368967870861',
    projectId: 'privy-96cd7',
    authDomain: 'privy-96cd7.firebaseapp.com',
    storageBucket: 'privy-96cd7.firebasestorage.app',
    measurementId: 'G-07QCK22PDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGR33a3LwoqnHx8jQP76H5xr6c7sUC_M',
    appId: '1:368967870861:android:4b1bd75a8da8438508f5c4',
    messagingSenderId: '368967870861',
    projectId: 'privy-96cd7',
    storageBucket: 'privy-96cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjXF2ZuM30bKGUc49auFpOInw5IaOahc',
    appId: '1:368967870861:ios:762a4a1529ef467308f5c4',
    messagingSenderId: '368967870861',
    projectId: 'privy-96cd7',
    storageBucket: 'privy-96cd7.firebasestorage.app',
    iosBundleId: 'com.example.privyChatChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjXF2ZuM30bKGUc49auFpOInw5IaOahc',
    appId: '1:368967870861:ios:762a4a1529ef467308f5c4',
    messagingSenderId: '368967870861',
    projectId: 'privy-96cd7',
    storageBucket: 'privy-96cd7.firebasestorage.app',
    iosBundleId: 'com.example.privyChatChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe9SrsGicW-GHCGY9jAYO3QfUKYi_reoA',
    appId: '1:368967870861:web:30fb356d37958d6b08f5c4',
    messagingSenderId: '368967870861',
    projectId: 'privy-96cd7',
    authDomain: 'privy-96cd7.firebaseapp.com',
    storageBucket: 'privy-96cd7.firebasestorage.app',
    measurementId: 'G-D13W875DP4',
  );
}
